# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Asia/Kolkata"
            --videoRecordingEnabled false


  mock:
    image: elgalu/google_adwords_mock
    depends_on:
      - zalenium
    ports:
      - 8080:8080
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080

        # HappayWebTests:
        #   image: "/happay-webtestsdocker:1.3"
        #   container_name: HappayWebTests
        #   depends_on:
        #     - zalenium
        #   environment:
        #     - HUB_HOST=zalenium
        #     - BROWSER=chrome
        #     - MODULE=testng.xml
        #   volumes:
      #     - ./allure-results:/usr/share/HATWebDocker/allure-results
      # Usage: